framework:
  mailer:
    envelope:
      sender: "Immersive Flashcards <support@immersive-flashcards.tech>"

    headers:
      From: "Immersive Flashcards <support@immersive-flashcards.tech>"
    dsn: "%env(MAILER_DSN)%"
when@test:
  framework:
    mailer:
      dsn: "null://null"
