framework:
  mailer:
    envelope:
      sender: "Immersive Flashcards <support@immersiveflashcards.com>"

    headers:
      From: "Immersive Flashcards <support@immersiveflashcards.com>"
    dsn: "%env(MAILER_DSN)%"
when@test:
  framework:
    mailer:
      dsn: "null://null"
