# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale_mappings:
        en:
            service_mappings:
                sentence_service: eng
                image_service: en
        fr:
            service_mappings:
                sentence_service: fra
                image_service: fr
        ru:
            service_mappings:
                sentence_service: rus
                image_service: ru
        it:
            service_mappings:
                sentence_service: ita
                image_service: it
        de:
            service_mappings:
                sentence_service: deu
                image_service: de
        es:
            service_mappings:
                sentence_service: spa
                image_service: es
        
        
services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
